resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/brooklyyounce/12FactorGoLibrary.git

- name: cf-deploy
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: younceb@goldmail.etsu.edu
    password: Brookly likes the number 47.
    organization: younceb-org
    space: development
    skip_cert_check: true
jobs:
- name: get-code-then-deploy-job
  serial: true
  plan:
  - {get: source-code, trigger: true}
  - put: cf-deploy
    params:
      manifest: source-code/manifest.yml
      path: source-code