---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: "1.8"

inputs:
- name: 12FactorGoLibrary

outputs:
- name: built-project

run:
  path: sh
  args:
    - -exc
    - |
      go env
      ls -a
      cd 12FactorGoLibrary
      ls -a
      export GOPATH=$PWD
      export PATH=$PATH:$GOPATH
      go env
      ls -lat
      cd src
      cd 12FactorGoLibrary
      ls -a
      go build book.go
      go build index.go
      ls -a
      cd $GOPATH
