---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: "latest"
    
inputs:
- name: go-library-source

outputs:
- name: built-project

run:
  path: sh
  args:
    - -exc
    - |
      chmod +x go-library-source/src/12FactorGoLibrary/ci/build.sh
run:
  path: go-library-source/src/12FactorGoLibrary/ci/build.sh
