---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: "latest"
    
inputs:
- name: go-library-source

outputs:
- name: built-project

run:
  path: sh
  args:
    - -exc
    - |
      cd go-library-source/src/12FactorGoLibrary/ci
      chmod +x build.sh
      ./build.sh
