---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang

inputs:
- name: go-library-source

outputs:
- name: built-project

run:
  path: sh
  args:
    - -exc
    - |
      go env
      ls -a
      cd go-library-source
      ls -a
      export GOPATH=$PWD
      export PATH=$PATH:$GOPATH
      go env
      ls -lat
      cd src
      cd 12FactorGoLibrary
      ls -a
      go build index.go
      ls -a
      cd $GOPATH
