---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: "latest"
    
inputs:
- name: go-library-source

outputs:
- name: built-project

run:
  path: sh
  args:
    - -exc
    - |
      set -e -u -x
      cd go-library-source
      export GOPATH=$PWD
      export PATH=$PATH:$GOPATH
      #export LIBRARY="cgidevlib:Password1@tcp(cgiprojdevlibrary.cxyeb3wmov3g.us-east-1.rds.amazonaws.com:9871)/cgiprojdevlibrary"
      cd src
      cd 12FactorGoLibrary
      go build index.go
      cd $GOPATH
