---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: "latest"
    
inputs:
- name: go-library-source

outputs:
- name: built-project

run:
  path: sh
  args:
    - -exc
    - |
      cd go-library-source
      export GOPATH=$PWD
      export PATH=$PATH:$GOPATH
      export LIBRARY="https://astaxie.gitbooks.io/build-web-application-with-golang/en/04.1.html"
      cd src
      cd 12FactorGoLibrary
      go build index.go
      cd $GOPATH
