---
resources:
- name: 12FactorGoLibrary
  type: git
  source:
    uri: https://github.com/christopherneuhardt/12FactorGoLibrary
    branch: test1
- name: deploy-app-dev
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: coxcs1@etsu.edu
    password: Dog.Bark1();
    organization: coxcs1-org
    space: development
    skip_cert_check: true
jobs:
- name: build-deploy-library
  serial: true
  plan:
  - {get: 12FactorGoLibrary, trigger: true}
  - task: build-and-deploy
    file: 12FactorGoLibrary/src/12FactorGoLibrary/ci/build.yml
  - put: deploy-app-dev
    params:
       manifest: 12FactorGoLibrary/src/12FactorGoLibrary/manifest.yml
       path: 12FactorGoLibrary/src/12FactorGoLibrary