---
resources:
- name: go-library-source
  type: git
  source:
    uri: https://github.com/christopherneuhardt/12FactorGoLibrary
    branch: master

jobs:
- name: deploy-test
  serial: true
  plan:
  - get: go-library-source
    trigger: true
  - task: functionalTestLibrary
    privileged: true
    file: go-library-source/src/12FactorGoLibrary/ci/functionalTest.yml