---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: "latest"

inputs:
- name: source-code

outputs:
- name: built-project

run:
  path: sh
  args:
    - -exc
    - |
      export GOPATH=$(pwd)/gopath:$(pwd)/gopath/src/github.com/christopherneuhardt/12FactorGoLibrary
      cd gopath/src/github.com/christopherneuhardt/12FactorGoLibrary
      go build -o built-project/library-go-app github.com/christopherneuhardt/12FactorGoLibrary