---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang

inputs:
- name: source-code

outputs:
- name: built-project

run:
  path: sh
  path: sh
  args:
    - -exc
    - |
      export GOPATH=$PWD/src
      go build -o built-project/library-go-app github.com/christopherneuhardt/12FactorGoLibrary/src