---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang

inputs:
- name: source-code

outputs:
- name: built-project

run:
  path: sh
  args:
    - -exc
    - |
      export GOPATH=$PWD
      go get github.com/christopherneuhardt/12FactorGoLibrary/src
      go build github.com/christopherneuhardt/12FactorGoLibrary/src