---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang

inputs:
- name: source-code

outputs:
- name: built-project

run:
  path: sh
  args:
    - -exc
    - |
      export GOPATH=$PWD
      ls -lat
      cd source-code
      ls -lat
      cd src
      ls -lat
      go build index.go
